### ISSUE TITLE
Internet Explorer issue initWorker()

### ISSUE THREAD

**Issue by FlorianBruckner** [andywer/threads.js#25]
I think I found another one. I run into this with IE9 with some polyfills for URL and WebWorker.

worker.js has this:

```
  initWorker() {
    try {
      this.worker = new window.Worker(slaveCodeDataUri);
    } catch (error) {
      const slaveScriptUrl = getConfig().fallback.slaveScriptUrl;
      if (slaveScriptUrl) {
        // try using the slave script file instead of the data URI
        this.worker = new window.Worker(slaveCodeDataUri);
      } else {
        // re-throw
        throw error;
      }
    }
  }

```

It rejects to use the data-url for creating the worker. The catch then reads the slave script URL (which I have set in the config). But it then again uses the slaveCodeDataUri for creating the worker. I believe it should use the slaveScriptUrl at this point.

**Comment by andywer** [comment]
Ohh, that seems like a rather stupid bug. Try the `develop` branch, please. I fixed this file.

**Comment by FlorianBruckner** [comment]
Yes, this fixes it. I still get "No thread logic initialized.", but this might as well be a problem in my setup.

**Comment by andywer** [comment]
`No thread logic initialized.` should only happen when you try to `.send()` before you `.run()`.

**Comment by FlorianBruckner** [comment]
This is the very same piece of code that runs in Chrome. I get this only with IE9 (with polyfills, which might very well be the reason for this)

**Comment by FlorianBruckner** [comment]
It seems to be a problem of the web worker polyfill I am using. It does not support importscripts (slave.js throws new Error('importScripts() not supported.')), which in turn triggers the message I am seeing in the console when the actual message is sent.

So not an issue with threads.js, but with the polyfill.
